import type { Metadata } from "next";
import { DM_Sans} from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { Toaster } from "@/components/ui/sonner";
import Provider from "./provider";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ai video generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <ClerkProvider>
      <html lang="en">
      <body
        className={`${dmSans.variable} font-sans bg-white dark:bg-black`}
      >
        <Provider>
          {children}
        </Provider>
        <Toaster position='top-center' richColors/>
      </body>
    </html>
     </ClerkProvider>
    
  );
}
